// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
////////////////////////////////////////////////////////////////////////////////

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: jwt_ml_dsa.proto

package jwt_ml_dsa_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// See https://www.rfc-editor.org/rfc/rfc9964.html#name-ml-dsa-algorithms
type JwtMlDsaAlgorithm int32

const (
	JwtMlDsaAlgorithm_ML_DSA_UNKNOWN JwtMlDsaAlgorithm = 0
	JwtMlDsaAlgorithm_ML_DSA44       JwtMlDsaAlgorithm = 1
	JwtMlDsaAlgorithm_ML_DSA65       JwtMlDsaAlgorithm = 2
	JwtMlDsaAlgorithm_ML_DSA87       JwtMlDsaAlgorithm = 3
)

// Enum value maps for JwtMlDsaAlgorithm.
var (
	JwtMlDsaAlgorithm_name = map[int32]string{
		0: "ML_DSA_UNKNOWN",
		1: "ML_DSA44",
		2: "ML_DSA65",
		3: "ML_DSA87",
	}
	JwtMlDsaAlgorithm_value = map[string]int32{
		"ML_DSA_UNKNOWN": 0,
		"ML_DSA44":       1,
		"ML_DSA65":       2,
		"ML_DSA87":       3,
	}
)

func (x JwtMlDsaAlgorithm) Enum() *JwtMlDsaAlgorithm {
	p := new(JwtMlDsaAlgorithm)
	*p = x
	return p
}

func (x JwtMlDsaAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JwtMlDsaAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_jwt_ml_dsa_proto_enumTypes[0].Descriptor()
}

func (JwtMlDsaAlgorithm) Type() protoreflect.EnumType {
	return &file_jwt_ml_dsa_proto_enumTypes[0]
}

func (x JwtMlDsaAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JwtMlDsaAlgorithm.Descriptor instead.
func (JwtMlDsaAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_jwt_ml_dsa_proto_rawDescGZIP(), []int{0}
}

type JwtMlDsaKeyFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Algorithm     JwtMlDsaAlgorithm      `protobuf:"varint,2,opt,name=algorithm,proto3,enum=google.crypto.tink.JwtMlDsaAlgorithm" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtMlDsaKeyFormat) Reset() {
	*x = JwtMlDsaKeyFormat{}
	mi := &file_jwt_ml_dsa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtMlDsaKeyFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtMlDsaKeyFormat) ProtoMessage() {}

func (x *JwtMlDsaKeyFormat) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_ml_dsa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtMlDsaKeyFormat.ProtoReflect.Descriptor instead.
func (*JwtMlDsaKeyFormat) Descriptor() ([]byte, []int) {
	return file_jwt_ml_dsa_proto_rawDescGZIP(), []int{0}
}

func (x *JwtMlDsaKeyFormat) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *JwtMlDsaKeyFormat) GetAlgorithm() JwtMlDsaAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return JwtMlDsaAlgorithm_ML_DSA_UNKNOWN
}

// key_type: type.googleapis.com/google.crypto.tink.JwtMlDsaPublicKey
type JwtMlDsaPublicKey struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Version       uint32                       `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Algorithm     JwtMlDsaAlgorithm            `protobuf:"varint,2,opt,name=algorithm,proto3,enum=google.crypto.tink.JwtMlDsaAlgorithm" json:"algorithm,omitempty"`
	KeyValue      []byte                       `protobuf:"bytes,3,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	CustomKid     *JwtMlDsaPublicKey_CustomKid `protobuf:"bytes,4,opt,name=custom_kid,json=customKid,proto3" json:"custom_kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtMlDsaPublicKey) Reset() {
	*x = JwtMlDsaPublicKey{}
	mi := &file_jwt_ml_dsa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtMlDsaPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtMlDsaPublicKey) ProtoMessage() {}

func (x *JwtMlDsaPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_ml_dsa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtMlDsaPublicKey.ProtoReflect.Descriptor instead.
func (*JwtMlDsaPublicKey) Descriptor() ([]byte, []int) {
	return file_jwt_ml_dsa_proto_rawDescGZIP(), []int{1}
}

func (x *JwtMlDsaPublicKey) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *JwtMlDsaPublicKey) GetAlgorithm() JwtMlDsaAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return JwtMlDsaAlgorithm_ML_DSA_UNKNOWN
}

func (x *JwtMlDsaPublicKey) GetKeyValue() []byte {
	if x != nil {
		return x.KeyValue
	}
	return nil
}

func (x *JwtMlDsaPublicKey) GetCustomKid() *JwtMlDsaPublicKey_CustomKid {
	if x != nil {
		return x.CustomKid
	}
	return nil
}

// key_type: type.googleapis.com/google.crypto.tink.JwtMlDsaPrivateKey
type JwtMlDsaPrivateKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Required. Note that this contains the seed used to generate the private
	// key, not the private key itself.
	KeyValue []byte `protobuf:"bytes,2,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"` // Placeholder for debug_redact.
	// The corresponding public key.
	PublicKey     *JwtMlDsaPublicKey `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtMlDsaPrivateKey) Reset() {
	*x = JwtMlDsaPrivateKey{}
	mi := &file_jwt_ml_dsa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtMlDsaPrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtMlDsaPrivateKey) ProtoMessage() {}

func (x *JwtMlDsaPrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_ml_dsa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtMlDsaPrivateKey.ProtoReflect.Descriptor instead.
func (*JwtMlDsaPrivateKey) Descriptor() ([]byte, []int) {
	return file_jwt_ml_dsa_proto_rawDescGZIP(), []int{2}
}

func (x *JwtMlDsaPrivateKey) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *JwtMlDsaPrivateKey) GetKeyValue() []byte {
	if x != nil {
		return x.KeyValue
	}
	return nil
}

func (x *JwtMlDsaPrivateKey) GetPublicKey() *JwtMlDsaPublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// Optional, custom kid header value to be used with "RAW" keys.
// "TINK" keys with this value set will be rejected.
type JwtMlDsaPublicKey_CustomKid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtMlDsaPublicKey_CustomKid) Reset() {
	*x = JwtMlDsaPublicKey_CustomKid{}
	mi := &file_jwt_ml_dsa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtMlDsaPublicKey_CustomKid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtMlDsaPublicKey_CustomKid) ProtoMessage() {}

func (x *JwtMlDsaPublicKey_CustomKid) ProtoReflect() protoreflect.Message {
	mi := &file_jwt_ml_dsa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtMlDsaPublicKey_CustomKid.ProtoReflect.Descriptor instead.
func (*JwtMlDsaPublicKey_CustomKid) Descriptor() ([]byte, []int) {
	return file_jwt_ml_dsa_proto_rawDescGZIP(), []int{1, 0}
}

func (x *JwtMlDsaPublicKey_CustomKid) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_jwt_ml_dsa_proto protoreflect.FileDescriptor

const file_jwt_ml_dsa_proto_rawDesc = "" +
	"\n" +
	"\x10jwt_ml_dsa.proto\x12\x12google.crypto.tink\"r\n" +
	"\x11JwtMlDsaKeyFormat\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12C\n" +
	"\talgorithm\x18\x02 \x01(\x0e2%.google.crypto.tink.JwtMlDsaAlgorithmR\talgorithm\"\x82\x02\n" +
	"\x11JwtMlDsaPublicKey\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12C\n" +
	"\talgorithm\x18\x02 \x01(\x0e2%.google.crypto.tink.JwtMlDsaAlgorithmR\talgorithm\x12\x1b\n" +
	"\tkey_value\x18\x03 \x01(\fR\bkeyValue\x12N\n" +
	"\n" +
	"custom_kid\x18\x04 \x01(\v2/.google.crypto.tink.JwtMlDsaPublicKey.CustomKidR\tcustomKid\x1a!\n" +
	"\tCustomKid\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x91\x01\n" +
	"\x12JwtMlDsaPrivateKey\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1b\n" +
	"\tkey_value\x18\x02 \x01(\fR\bkeyValue\x12D\n" +
	"\n" +
	"public_key\x18\x03 \x01(\v2%.google.crypto.tink.JwtMlDsaPublicKeyR\tpublicKey*Q\n" +
	"\x11JwtMlDsaAlgorithm\x12\x12\n" +
	"\x0eML_DSA_UNKNOWN\x10\x00\x12\f\n" +
	"\bML_DSA44\x10\x01\x12\f\n" +
	"\bML_DSA65\x10\x02\x12\f\n" +
	"\bML_DSA87\x10\x03B]\n" +
	"\x1ccom.google.crypto.tink.protoP\x01Z;github.com/tink-crypto/tink-go/v2/proto/jwt_ml_dsa_go_protob\x06proto3"

var (
	file_jwt_ml_dsa_proto_rawDescOnce sync.Once
	file_jwt_ml_dsa_proto_rawDescData []byte
)

func file_jwt_ml_dsa_proto_rawDescGZIP() []byte {
	file_jwt_ml_dsa_proto_rawDescOnce.Do(func() {
		file_jwt_ml_dsa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jwt_ml_dsa_proto_rawDesc), len(file_jwt_ml_dsa_proto_rawDesc)))
	})
	return file_jwt_ml_dsa_proto_rawDescData
}

var file_jwt_ml_dsa_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jwt_ml_dsa_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jwt_ml_dsa_proto_goTypes = []any{
	(JwtMlDsaAlgorithm)(0),              // 0: google.crypto.tink.JwtMlDsaAlgorithm
	(*JwtMlDsaKeyFormat)(nil),           // 1: google.crypto.tink.JwtMlDsaKeyFormat
	(*JwtMlDsaPublicKey)(nil),           // 2: google.crypto.tink.JwtMlDsaPublicKey
	(*JwtMlDsaPrivateKey)(nil),          // 3: google.crypto.tink.JwtMlDsaPrivateKey
	(*JwtMlDsaPublicKey_CustomKid)(nil), // 4: google.crypto.tink.JwtMlDsaPublicKey.CustomKid
}
var file_jwt_ml_dsa_proto_depIdxs = []int32{
	0, // 0: google.crypto.tink.JwtMlDsaKeyFormat.algorithm:type_name -> google.crypto.tink.JwtMlDsaAlgorithm
	0, // 1: google.crypto.tink.JwtMlDsaPublicKey.algorithm:type_name -> google.crypto.tink.JwtMlDsaAlgorithm
	4, // 2: google.crypto.tink.JwtMlDsaPublicKey.custom_kid:type_name -> google.crypto.tink.JwtMlDsaPublicKey.CustomKid
	2, // 3: google.crypto.tink.JwtMlDsaPrivateKey.public_key:type_name -> google.crypto.tink.JwtMlDsaPublicKey
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_jwt_ml_dsa_proto_init() }
func file_jwt_ml_dsa_proto_init() {
	if File_jwt_ml_dsa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jwt_ml_dsa_proto_rawDesc), len(file_jwt_ml_dsa_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jwt_ml_dsa_proto_goTypes,
		DependencyIndexes: file_jwt_ml_dsa_proto_depIdxs,
		EnumInfos:         file_jwt_ml_dsa_proto_enumTypes,
		MessageInfos:      file_jwt_ml_dsa_proto_msgTypes,
	}.Build()
	File_jwt_ml_dsa_proto = out.File
	file_jwt_ml_dsa_proto_goTypes = nil
	file_jwt_ml_dsa_proto_depIdxs = nil
}
