// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////

// Protos for Composite Module-Lattice Digital Signature Algorithm (ML-DSA).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: composite_ml_dsa.proto

package composite_ml_dsa_go_proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	ml_dsa_go_proto "github.com/tink-crypto/tink-go/v2/proto/ml_dsa_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LINT: LEGACY_NAMES
type CompositeMlDsaClassicalAlgorithm int32

const (
	CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_UNKNOWN CompositeMlDsaClassicalAlgorithm = 0
	CompositeMlDsaClassicalAlgorithm_ED25519                     CompositeMlDsaClassicalAlgorithm = 1
	CompositeMlDsaClassicalAlgorithm_ECDSA_P256                  CompositeMlDsaClassicalAlgorithm = 2
	CompositeMlDsaClassicalAlgorithm_ECDSA_P384                  CompositeMlDsaClassicalAlgorithm = 3
	CompositeMlDsaClassicalAlgorithm_ECDSA_P521                  CompositeMlDsaClassicalAlgorithm = 4
	CompositeMlDsaClassicalAlgorithm_RSA_3072_PSS                CompositeMlDsaClassicalAlgorithm = 5
	CompositeMlDsaClassicalAlgorithm_RSA_4096_PSS                CompositeMlDsaClassicalAlgorithm = 6
	CompositeMlDsaClassicalAlgorithm_RSA_3072_PKCS1              CompositeMlDsaClassicalAlgorithm = 7
	CompositeMlDsaClassicalAlgorithm_RSA_4096_PKCS1              CompositeMlDsaClassicalAlgorithm = 8
)

// Enum value maps for CompositeMlDsaClassicalAlgorithm.
var (
	CompositeMlDsaClassicalAlgorithm_name = map[int32]string{
		0: "CLASSICAL_ALGORITHM_UNKNOWN",
		1: "ED25519",
		2: "ECDSA_P256",
		3: "ECDSA_P384",
		4: "ECDSA_P521",
		5: "RSA_3072_PSS",
		6: "RSA_4096_PSS",
		7: "RSA_3072_PKCS1",
		8: "RSA_4096_PKCS1",
	}
	CompositeMlDsaClassicalAlgorithm_value = map[string]int32{
		"CLASSICAL_ALGORITHM_UNKNOWN": 0,
		"ED25519":                     1,
		"ECDSA_P256":                  2,
		"ECDSA_P384":                  3,
		"ECDSA_P521":                  4,
		"RSA_3072_PSS":                5,
		"RSA_4096_PSS":                6,
		"RSA_3072_PKCS1":              7,
		"RSA_4096_PKCS1":              8,
	}
)

func (x CompositeMlDsaClassicalAlgorithm) Enum() *CompositeMlDsaClassicalAlgorithm {
	p := new(CompositeMlDsaClassicalAlgorithm)
	*p = x
	return p
}

func (x CompositeMlDsaClassicalAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompositeMlDsaClassicalAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_composite_ml_dsa_proto_enumTypes[0].Descriptor()
}

func (CompositeMlDsaClassicalAlgorithm) Type() protoreflect.EnumType {
	return &file_composite_ml_dsa_proto_enumTypes[0]
}

func (x CompositeMlDsaClassicalAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompositeMlDsaClassicalAlgorithm.Descriptor instead.
func (CompositeMlDsaClassicalAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_composite_ml_dsa_proto_rawDescGZIP(), []int{0}
}

type CompositeMlDsaParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	MlDsaInstance ml_dsa_go_proto.MlDsaInstance `protobuf:"varint,1,opt,name=ml_dsa_instance,json=mlDsaInstance,proto3,enum=google.crypto.tink.MlDsaInstance" json:"ml_dsa_instance,omitempty"`
	// Required.
	CompositeMlDsaClassicalAlgorithm CompositeMlDsaClassicalAlgorithm `protobuf:"varint,2,opt,name=classical_algorithm,json=classicalAlgorithm,proto3,enum=google.crypto.tink.CompositeMlDsaClassicalAlgorithm" json:"classical_algorithm,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *CompositeMlDsaParams) Reset() {
	*x = CompositeMlDsaParams{}
	mi := &file_composite_ml_dsa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeMlDsaParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeMlDsaParams) ProtoMessage() {}

func (x *CompositeMlDsaParams) ProtoReflect() protoreflect.Message {
	mi := &file_composite_ml_dsa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeMlDsaParams.ProtoReflect.Descriptor instead.
func (*CompositeMlDsaParams) Descriptor() ([]byte, []int) {
	return file_composite_ml_dsa_proto_rawDescGZIP(), []int{0}
}

func (x *CompositeMlDsaParams) GetMlDsaInstance() ml_dsa_go_proto.MlDsaInstance {
	if x != nil {
		return x.MlDsaInstance
	}
	return ml_dsa_go_proto.MlDsaInstance_ML_DSA_UNKNOWN_INSTANCE
}

func (x *CompositeMlDsaParams) GetCompositeMlDsaClassicalAlgorithm() CompositeMlDsaClassicalAlgorithm {
	if x != nil {
		return x.CompositeMlDsaClassicalAlgorithm
	}
	return CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_UNKNOWN
}

type CompositeMlDsaKeyFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Required.
	Params        *CompositeMlDsaParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeMlDsaKeyFormat) Reset() {
	*x = CompositeMlDsaKeyFormat{}
	mi := &file_composite_ml_dsa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeMlDsaKeyFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeMlDsaKeyFormat) ProtoMessage() {}

func (x *CompositeMlDsaKeyFormat) ProtoReflect() protoreflect.Message {
	mi := &file_composite_ml_dsa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeMlDsaKeyFormat.ProtoReflect.Descriptor instead.
func (*CompositeMlDsaKeyFormat) Descriptor() ([]byte, []int) {
	return file_composite_ml_dsa_proto_rawDescGZIP(), []int{1}
}

func (x *CompositeMlDsaKeyFormat) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CompositeMlDsaKeyFormat) GetParams() *CompositeMlDsaParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// key_type: type.googleapis.com/google.crypto.tink.CompositeMlDsaPublicKey
type CompositeMlDsaPublicKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Required.
	MldsaPublicKey []byte `protobuf:"bytes,2,opt,name=mldsa_public_key,json=mldsaPublicKey,proto3" json:"mldsa_public_key,omitempty"`
	// Required.
	ClassicalPublicKey []byte `protobuf:"bytes,3,opt,name=classical_public_key,json=classicalPublicKey,proto3" json:"classical_public_key,omitempty"`
	// Required.
	Params        *CompositeMlDsaParams `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeMlDsaPublicKey) Reset() {
	*x = CompositeMlDsaPublicKey{}
	mi := &file_composite_ml_dsa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeMlDsaPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeMlDsaPublicKey) ProtoMessage() {}

func (x *CompositeMlDsaPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_composite_ml_dsa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeMlDsaPublicKey.ProtoReflect.Descriptor instead.
func (*CompositeMlDsaPublicKey) Descriptor() ([]byte, []int) {
	return file_composite_ml_dsa_proto_rawDescGZIP(), []int{2}
}

func (x *CompositeMlDsaPublicKey) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CompositeMlDsaPublicKey) GetMldsaPublicKey() []byte {
	if x != nil {
		return x.MldsaPublicKey
	}
	return nil
}

func (x *CompositeMlDsaPublicKey) GetClassicalPublicKey() []byte {
	if x != nil {
		return x.ClassicalPublicKey
	}
	return nil
}

func (x *CompositeMlDsaPublicKey) GetParams() *CompositeMlDsaParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// key_type: type.googleapis.com/google.crypto.tink.CompositeMlDsaPrivateKey
type CompositeMlDsaPrivateKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Required. Note that this contains the seed used to generate the private
	// key, not the private key itself.
	MldsaPrivateKey []byte `protobuf:"bytes,2,opt,name=mldsa_private_key,json=mldsaPrivateKey,proto3" json:"mldsa_private_key,omitempty"`
	// Required.
	ClassicalPrivateKey []byte `protobuf:"bytes,3,opt,name=classical_private_key,json=classicalPrivateKey,proto3" json:"classical_private_key,omitempty"`
	// The corresponding public key.
	PublicKey     *CompositeMlDsaPublicKey `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeMlDsaPrivateKey) Reset() {
	*x = CompositeMlDsaPrivateKey{}
	mi := &file_composite_ml_dsa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeMlDsaPrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeMlDsaPrivateKey) ProtoMessage() {}

func (x *CompositeMlDsaPrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_composite_ml_dsa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeMlDsaPrivateKey.ProtoReflect.Descriptor instead.
func (*CompositeMlDsaPrivateKey) Descriptor() ([]byte, []int) {
	return file_composite_ml_dsa_proto_rawDescGZIP(), []int{3}
}

func (x *CompositeMlDsaPrivateKey) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CompositeMlDsaPrivateKey) GetMldsaPrivateKey() []byte {
	if x != nil {
		return x.MldsaPrivateKey
	}
	return nil
}

func (x *CompositeMlDsaPrivateKey) GetClassicalPrivateKey() []byte {
	if x != nil {
		return x.ClassicalPrivateKey
	}
	return nil
}

func (x *CompositeMlDsaPrivateKey) GetPublicKey() *CompositeMlDsaPublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_composite_ml_dsa_proto protoreflect.FileDescriptor

const file_composite_ml_dsa_proto_rawDesc = "" +
	"\n" +
	"\x18composite_ml_dsa.proto\x12\x12google.crypto.tink\x1a\fml_dsa.proto"

var (
	file_composite_ml_dsa_proto_rawDescOnce sync.Once
	file_composite_ml_dsa_proto_rawDescData []byte
)

func file_composite_ml_dsa_proto_rawDescGZIP() []byte {
	file_composite_ml_dsa_proto_rawDescOnce.Do(func() {
		file_composite_ml_dsa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_composite_ml_dsa_proto_rawDesc), len(file_composite_ml_dsa_proto_rawDesc)))
	})
	return file_composite_ml_dsa_proto_rawDescData
}

var file_composite_ml_dsa_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_composite_ml_dsa_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_composite_ml_dsa_proto_goTypes = []any{
	(CompositeMlDsaClassicalAlgorithm)(0), // 0: google.crypto.tink.CompositeMlDsaClassicalAlgorithm
	(*CompositeMlDsaParams)(nil),          // 1: google.crypto.tink.CompositeMlDsaParams
	(*CompositeMlDsaKeyFormat)(nil),       // 2: google.crypto.tink.CompositeMlDsaKeyFormat
	(*CompositeMlDsaPublicKey)(nil),       // 3: google.crypto.tink.CompositeMlDsaPublicKey
	(*CompositeMlDsaPrivateKey)(nil),      // 4: google.crypto.tink.CompositeMlDsaPrivateKey
	(ml_dsa_go_proto.MlDsaInstance)(0),    // 5: google.crypto.tink.MlDsaInstance
}
var file_composite_ml_dsa_proto_depIdxs = []int32{
	5, // 0: google.crypto.tink.CompositeMlDsaParams.ml_dsa_instance:type_name -> google.crypto.tink.MlDsaInstance
	0, // 1: google.crypto.tink.CompositeMlDsaParams.classical_algorithm:type_name -> google.crypto.tink.CompositeMlDsaClassicalAlgorithm
	1, // 2: google.crypto.tink.CompositeMlDsaKeyFormat.params:type_name -> google.crypto.tink.CompositeMlDsaParams
	1, // 3: google.crypto.tink.CompositeMlDsaPublicKey.params:type_name -> google.crypto.tink.CompositeMlDsaParams
	3, // 4: google.crypto.tink.CompositeMlDsaPrivateKey.public_key:type_name -> google.crypto.tink.CompositeMlDsaPublicKey
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extended
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_composite_ml_dsa_proto_init() }
func file_composite_ml_dsa_proto_init() {
	if File_composite_ml_dsa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_composite_ml_dsa_proto_rawDesc), len(file_composite_ml_dsa_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_composite_ml_dsa_proto_goTypes,
		DependencyIndexes: file_composite_ml_dsa_proto_depIdxs,
		EnumInfos:         file_composite_ml_dsa_proto_enumTypes,
		MessageInfos:      file_composite_ml_dsa_proto_msgTypes,
	}.Build()
	File_composite_ml_dsa_proto = out.File
	file_composite_ml_dsa_proto_goTypes = nil
	file_composite_ml_dsa_proto_depIdxs = nil
}
