// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
////////////////////////////////////////////////////////////////////////////////

// Protos for Composite Module-Lattice Digital Signature Algorithm (Composite
// ML-DSA). See
// https://datatracker.ietf.org/doc/html/draft-ietf-lamps-pq-composite-sigs-14.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: third_party/tink/proto/composite_ml_dsa.proto

package composite_ml_dsa_go_proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	ml_dsa_go_proto "github.com/tink-crypto/tink-go/v2/proto/ml_dsa_go_proto"
	tink_go_proto "github.com/tink-crypto/tink-go/v2/proto/tink_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LINT: LEGACY_NAMES
type CompositeMlDsaClassicalAlgorithm int32

const (
	CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_UNKNOWN       CompositeMlDsaClassicalAlgorithm = 0
	CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_ED25519       CompositeMlDsaClassicalAlgorithm = 1
	CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_ECDSA_P256    CompositeMlDsaClassicalAlgorithm = 2
	CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_ECDSA_P384    CompositeMlDsaClassicalAlgorithm = 3
	CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_ECDSA_P521    CompositeMlDsaClassicalAlgorithm = 4
	CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_RSA3072_PSS   CompositeMlDsaClassicalAlgorithm = 5
	CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_RSA4096_PSS   CompositeMlDsaClassicalAlgorithm = 6
	CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_RSA3072_PKCS1 CompositeMlDsaClassicalAlgorithm = 7
	CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_RSA4096_PKCS1 CompositeMlDsaClassicalAlgorithm = 8
)

// Enum value maps for CompositeMlDsaClassicalAlgorithm.
var (
	CompositeMlDsaClassicalAlgorithm_name = map[int32]string{
		0: "CLASSICAL_ALGORITHM_UNKNOWN",
		1: "CLASSICAL_ALGORITHM_ED25519",
		2: "CLASSICAL_ALGORITHM_ECDSA_P256",
		3: "CLASSICAL_ALGORITHM_ECDSA_P384",
		4: "CLASSICAL_ALGORITHM_ECDSA_P521",
		5: "CLASSICAL_ALGORITHM_RSA3072_PSS",
		6: "CLASSICAL_ALGORITHM_RSA4096_PSS",
		7: "CLASSICAL_ALGORITHM_RSA3072_PKCS1",
		8: "CLASSICAL_ALGORITHM_RSA4096_PKCS1",
	}
	CompositeMlDsaClassicalAlgorithm_value = map[string]int32{
		"CLASSICAL_ALGORITHM_UNKNOWN":       0,
		"CLASSICAL_ALGORITHM_ED25519":       1,
		"CLASSICAL_ALGORITHM_ECDSA_P256":    2,
		"CLASSICAL_ALGORITHM_ECDSA_P384":    3,
		"CLASSICAL_ALGORITHM_ECDSA_P521":    4,
		"CLASSICAL_ALGORITHM_RSA3072_PSS":   5,
		"CLASSICAL_ALGORITHM_RSA4096_PSS":   6,
		"CLASSICAL_ALGORITHM_RSA3072_PKCS1": 7,
		"CLASSICAL_ALGORITHM_RSA4096_PKCS1": 8,
	}
)

func (x CompositeMlDsaClassicalAlgorithm) Enum() *CompositeMlDsaClassicalAlgorithm {
	p := new(CompositeMlDsaClassicalAlgorithm)
	*p = x
	return p
}

func (x CompositeMlDsaClassicalAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompositeMlDsaClassicalAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_third_party_tink_proto_composite_ml_dsa_proto_enumTypes[0].Descriptor()
}

func (CompositeMlDsaClassicalAlgorithm) Type() protoreflect.EnumType {
	return &file_third_party_tink_proto_composite_ml_dsa_proto_enumTypes[0]
}

func (x CompositeMlDsaClassicalAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompositeMlDsaClassicalAlgorithm.Descriptor instead.
func (CompositeMlDsaClassicalAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_third_party_tink_proto_composite_ml_dsa_proto_rawDescGZIP(), []int{0}
}

type CompositeMlDsaKeyFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Required.
	Params        *CompositeMlDsaParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeMlDsaKeyFormat) Reset() {
	*x = CompositeMlDsaKeyFormat{}
	mi := &file_third_party_tink_proto_composite_ml_dsa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeMlDsaKeyFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeMlDsaKeyFormat) ProtoMessage() {}

func (x *CompositeMlDsaKeyFormat) ProtoReflect() protoreflect.Message {
	mi := &file_third_party_tink_proto_composite_ml_dsa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeMlDsaKeyFormat.ProtoReflect.Descriptor instead.
func (*CompositeMlDsaKeyFormat) Descriptor() ([]byte, []int) {
	return file_third_party_tink_proto_composite_ml_dsa_proto_rawDescGZIP(), []int{0}
}

func (x *CompositeMlDsaKeyFormat) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CompositeMlDsaKeyFormat) GetParams() *CompositeMlDsaParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// See
// https://datatracker.ietf.org/doc/html/draft-ietf-lamps-pq-composite-sigs-14#section-6
// for allowed combinations/OIDs.
type CompositeMlDsaParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	MlDsaInstance ml_dsa_go_proto.MlDsaInstance `protobuf:"varint,1,opt,name=ml_dsa_instance,json=mlDsaInstance,proto3,enum=google.crypto.tink.MlDsaInstance" json:"ml_dsa_instance,omitempty"`
	// Required.
	ClassicalAlgorithm CompositeMlDsaClassicalAlgorithm `protobuf:"varint,2,opt,name=classical_algorithm,json=classicalAlgorithm,proto3,enum=google.crypto.tink.CompositeMlDsaClassicalAlgorithm" json:"classical_algorithm,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompositeMlDsaParams) Reset() {
	*x = CompositeMlDsaParams{}
	mi := &file_third_party_tink_proto_composite_ml_dsa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeMlDsaParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeMlDsaParams) ProtoMessage() {}

func (x *CompositeMlDsaParams) ProtoReflect() protoreflect.Message {
	mi := &file_third_party_tink_proto_composite_ml_dsa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeMlDsaParams.ProtoReflect.Descriptor instead.
func (*CompositeMlDsaParams) Descriptor() ([]byte, []int) {
	return file_third_party_tink_proto_composite_ml_dsa_proto_rawDescGZIP(), []int{1}
}

func (x *CompositeMlDsaParams) GetMlDsaInstance() ml_dsa_go_proto.MlDsaInstance {
	if x != nil {
		return x.MlDsaInstance
	}
	return ml_dsa_go_proto.MlDsaInstance(0)
}

func (x *CompositeMlDsaParams) GetClassicalAlgorithm() CompositeMlDsaClassicalAlgorithm {
	if x != nil {
		return x.ClassicalAlgorithm
	}
	return CompositeMlDsaClassicalAlgorithm_CLASSICAL_ALGORITHM_UNKNOWN
}

type CompositeMlDsaPublicKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Required.
	MlDsaPublicKey *tink_go_proto.KeyData `protobuf:"bytes,2,opt,name=ml_dsa_public_key,json=mlDsaPublicKey,proto3" json:"ml_dsa_public_key,omitempty"`
	// Required.
	// Contains one of EcdsaPublicKey, Ed25519PublicKey, RsaSsaPssPublicKey, or
	// RsaSsaPkcs1PublicKey.
	ClassicalPublicKey *tink_go_proto.KeyData `protobuf:"bytes,3,opt,name=classical_public_key,json=classicalPublicKey,proto3" json:"classical_public_key,omitempty"`
	// Required.
	Params        *CompositeMlDsaParams `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeMlDsaPublicKey) Reset() {
	*x = CompositeMlDsaPublicKey{}
	mi := &file_third_party_tink_proto_composite_ml_dsa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeMlDsaPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeMlDsaPublicKey) ProtoMessage() {}

func (x *CompositeMlDsaPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_third_party_tink_proto_composite_ml_dsa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeMlDsaPublicKey.ProtoReflect.Descriptor instead.
func (*CompositeMlDsaPublicKey) Descriptor() ([]byte, []int) {
	return file_third_party_tink_proto_composite_ml_dsa_proto_rawDescGZIP(), []int{2}
}

func (x *CompositeMlDsaPublicKey) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CompositeMlDsaPublicKey) GetMlDsaPublicKey() *tink_go_proto.KeyData {
	if x != nil {
		return x.MlDsaPublicKey
	}
	return nil
}

func (x *CompositeMlDsaPublicKey) GetClassicalPublicKey() *tink_go_proto.KeyData {
	if x != nil {
		return x.ClassicalPublicKey
	}
	return nil
}

func (x *CompositeMlDsaPublicKey) GetParams() *CompositeMlDsaParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type CompositeMlDsaPrivateKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Required.
	MlDsaPrivateKey *tink_go_proto.KeyData `protobuf:"bytes,2,opt,name=ml_dsa_private_key,json=mlDsaPrivateKey,proto3" json:"ml_dsa_private_key,omitempty"`
	// Required.
	// Contains one of EcdsaPrivateKey, Ed25519PrivateKey, RsaSsaPssPrivateKey,
	// or RsaSsaPkcs1PrivateKey.
	ClassicalPrivateKey *tink_go_proto.KeyData `protobuf:"bytes,3,opt,name=classical_private_key,json=classicalPrivateKey,proto3" json:"classical_private_key,omitempty"`
	// Required.
	Params        *CompositeMlDsaParams `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeMlDsaPrivateKey) Reset() {
	*x = CompositeMlDsaPrivateKey{}
	mi := &file_third_party_tink_proto_composite_ml_dsa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeMlDsaPrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeMlDsaPrivateKey) ProtoMessage() {}

func (x *CompositeMlDsaPrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_third_party_tink_proto_composite_ml_dsa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeMlDsaPrivateKey.ProtoReflect.Descriptor instead.
func (*CompositeMlDsaPrivateKey) Descriptor() ([]byte, []int) {
	return file_third_party_tink_proto_composite_ml_dsa_proto_rawDescGZIP(), []int{3}
}

func (x *CompositeMlDsaPrivateKey) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CompositeMlDsaPrivateKey) GetMlDsaPrivateKey() *tink_go_proto.KeyData {
	if x != nil {
		return x.MlDsaPrivateKey
	}
	return nil
}

func (x *CompositeMlDsaPrivateKey) GetClassicalPrivateKey() *tink_go_proto.KeyData {
	if x != nil {
		return x.ClassicalPrivateKey
	}
	return nil
}

func (x *CompositeMlDsaPrivateKey) GetParams() *CompositeMlDsaParams {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_third_party_tink_proto_composite_ml_dsa_proto protoreflect.FileDescriptor

const file_third_party_tink_proto_composite_ml_dsa_proto_rawDesc = "" +
	"\n" +
	"-third_party/tink/proto/composite_ml_dsa.proto\x12\x12google.crypto.tink\x1a#third_party/tink/proto/ml_dsa.proto\x1a!third_party/tink/proto/tink.proto\"u\n" +
	"\x17CompositeMlDsaKeyFormat\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12@\n" +
	"\x06params\x18\x02 \x01(\v2(.google.crypto.tink.CompositeMlDsaParamsR\x06params\"\xc8\x01\n" +
	"\x14CompositeMlDsaParams\x12I\n" +
	"\x0fml_dsa_instance\x18\x01 \x01(\x0e2!.google.crypto.tink.MlDsaInstanceR\rmlDsaInstance\x12e\n" +
	"\x13classical_algorithm\x18\x02 \x01(\x0e24.google.crypto.tink.CompositeMlDsaClassicalAlgorithmR\x12classicalAlgorithm\"\x8c\x02\n" +
	"\x17CompositeMlDsaPublicKey\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12F\n" +
	"\x11ml_dsa_public_key\x18\x02 \x01(\v2\x1b.google.crypto.tink.KeyDataR\x0emlDsaPublicKey\x12M\n" +
	"\x14classical_public_key\x18\x03 \x01(\v2\x1b.google.crypto.tink.KeyDataR\x12classicalPublicKey\x12@\n" +
	"\x06params\x18\x04 \x01(\v2(.google.crypto.tink.CompositeMlDsaParamsR\x06params\"\x91\x02\n" +
	"\x18CompositeMlDsaPrivateKey\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12H\n" +
	"\x12ml_dsa_private_key\x18\x02 \x01(\v2\x1b.google.crypto.tink.KeyDataR\x0fmlDsaPrivateKey\x12O\n" +
	"\x15classical_private_key\x18\x03 \x01(\v2\x1b.google.crypto.tink.KeyDataR\x13classicalPrivateKey\x12@\n" +
	"\x06params\x18\x04 \x01(\v2(.google.crypto.tink.CompositeMlDsaParamsR\x06params*\xe8\x02\n" +
	" CompositeMlDsaClassicalAlgorithm\x12\x1f\n" +
	"\x1bCLASSICAL_ALGORITHM_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bCLASSICAL_ALGORITHM_ED25519\x10\x01\x12\"\n" +
	"\x1eCLASSICAL_ALGORITHM_ECDSA_P256\x10\x02\x12\"\n" +
	"\x1eCLASSICAL_ALGORITHM_ECDSA_P384\x10\x03\x12\"\n" +
	"\x1eCLASSICAL_ALGORITHM_ECDSA_P521\x10\x04\x12#\n" +
	"\x1fCLASSICAL_ALGORITHM_RSA3072_PSS\x10\x05\x12#\n" +
	"\x1fCLASSICAL_ALGORITHM_RSA4096_PSS\x10\x06\x12%\n" +
	"!CLASSICAL_ALGORITHM_RSA3072_PKCS1\x10\a\x12%\n" +
	"!CLASSICAL_ALGORITHM_RSA4096_PKCS1\x10\bBc\n" +
	"\x1ccom.google.crypto.tink.protoP\x01ZAgithub.com/tink-crypto/tink-go/v2/proto/composite_ml_dsa_go_protob\x06proto3"

var (
	file_third_party_tink_proto_composite_ml_dsa_proto_rawDescOnce sync.Once
	file_third_party_tink_proto_composite_ml_dsa_proto_rawDescData []byte
)

func file_third_party_tink_proto_composite_ml_dsa_proto_rawDescGZIP() []byte {
	file_third_party_tink_proto_composite_ml_dsa_proto_rawDescOnce.Do(func() {
		file_third_party_tink_proto_composite_ml_dsa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_third_party_tink_proto_composite_ml_dsa_proto_rawDesc), len(file_third_party_tink_proto_composite_ml_dsa_proto_rawDesc)))
	})
	return file_third_party_tink_proto_composite_ml_dsa_proto_rawDescData
}

var file_third_party_tink_proto_composite_ml_dsa_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_third_party_tink_proto_composite_ml_dsa_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_third_party_tink_proto_composite_ml_dsa_proto_goTypes = []any{
	(CompositeMlDsaClassicalAlgorithm)(0), // 0: google.crypto.tink.CompositeMlDsaClassicalAlgorithm
	(*CompositeMlDsaKeyFormat)(nil),       // 1: google.crypto.tink.CompositeMlDsaKeyFormat
	(*CompositeMlDsaParams)(nil),          // 2: google.crypto.tink.CompositeMlDsaParams
	(*CompositeMlDsaPublicKey)(nil),       // 3: google.crypto.tink.CompositeMlDsaPublicKey
	(*CompositeMlDsaPrivateKey)(nil),      // 4: google.crypto.tink.CompositeMlDsaPrivateKey
	(ml_dsa_go_proto.MlDsaInstance)(0),    // 5: google.crypto.tink.MlDsaInstance
	(*tink_go_proto.KeyData)(nil),         // 6: google.crypto.tink.KeyData
}
var file_third_party_tink_proto_composite_ml_dsa_proto_depIdxs = []int32{
	2, // 0: google.crypto.tink.CompositeMlDsaKeyFormat.params:type_name -> google.crypto.tink.CompositeMlDsaParams
	5, // 1: google.crypto.tink.CompositeMlDsaParams.ml_dsa_instance:type_name -> google.crypto.tink.MlDsaInstance
	0, // 2: google.crypto.tink.CompositeMlDsaParams.classical_algorithm:type_name -> google.crypto.tink.CompositeMlDsaClassicalAlgorithm
	6, // 3: google.crypto.tink.CompositeMlDsaPublicKey.ml_dsa_public_key:type_name -> google.crypto.tink.KeyData
	6, // 4: google.crypto.tink.CompositeMlDsaPublicKey.classical_public_key:type_name -> google.crypto.tink.KeyData
	2, // 5: google.crypto.tink.CompositeMlDsaPublicKey.params:type_name -> google.crypto.tink.CompositeMlDsaParams
	6, // 6: google.crypto.tink.CompositeMlDsaPrivateKey.ml_dsa_private_key:type_name -> google.crypto.tink.KeyData
	6, // 7: google.crypto.tink.CompositeMlDsaPrivateKey.classical_private_key:type_name -> google.crypto.tink.KeyData
	2, // 8: google.crypto.tink.CompositeMlDsaPrivateKey.params:type_name -> google.crypto.tink.CompositeMlDsaParams
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_third_party_tink_proto_composite_ml_dsa_proto_init() }
func file_third_party_tink_proto_composite_ml_dsa_proto_init() {
	if File_third_party_tink_proto_composite_ml_dsa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_third_party_tink_proto_composite_ml_dsa_proto_rawDesc), len(file_third_party_tink_proto_composite_ml_dsa_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_third_party_tink_proto_composite_ml_dsa_proto_goTypes,
		DependencyIndexes: file_third_party_tink_proto_composite_ml_dsa_proto_depIdxs,
		EnumInfos:         file_third_party_tink_proto_composite_ml_dsa_proto_enumTypes,
		MessageInfos:      file_third_party_tink_proto_composite_ml_dsa_proto_msgTypes,
	}.Build()
	File_third_party_tink_proto_composite_ml_dsa_proto = out.File
	file_third_party_tink_proto_composite_ml_dsa_proto_goTypes = nil
	file_third_party_tink_proto_composite_ml_dsa_proto_depIdxs = nil
}
