// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
////////////////////////////////////////////////////////////////////////////////

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: x_aes_gcm.proto

package x_aes_gcm_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XAesGcmParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Must be at least 8 bytes and at most 12 bytes.
	SaltSize uint32 `protobuf:"varint,1,opt,name=salt_size,json=saltSize,proto3" json:"salt_size,omitempty"`
}

func (x *XAesGcmParams) Reset() {
	*x = XAesGcmParams{}
	mi := &file_x_aes_gcm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XAesGcmParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XAesGcmParams) ProtoMessage() {}

func (x *XAesGcmParams) ProtoReflect() protoreflect.Message {
	mi := &file_x_aes_gcm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XAesGcmParams.ProtoReflect.Descriptor instead.
func (*XAesGcmParams) Descriptor() ([]byte, []int) {
	return file_x_aes_gcm_proto_rawDescGZIP(), []int{0}
}

func (x *XAesGcmParams) GetSaltSize() uint32 {
	if x != nil {
		return x.SaltSize
	}
	return 0
}

type XAesGcmKeyFormat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint32         `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Params  *XAesGcmParams `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *XAesGcmKeyFormat) Reset() {
	*x = XAesGcmKeyFormat{}
	mi := &file_x_aes_gcm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XAesGcmKeyFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XAesGcmKeyFormat) ProtoMessage() {}

func (x *XAesGcmKeyFormat) ProtoReflect() protoreflect.Message {
	mi := &file_x_aes_gcm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XAesGcmKeyFormat.ProtoReflect.Descriptor instead.
func (*XAesGcmKeyFormat) Descriptor() ([]byte, []int) {
	return file_x_aes_gcm_proto_rawDescGZIP(), []int{1}
}

func (x *XAesGcmKeyFormat) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *XAesGcmKeyFormat) GetParams() *XAesGcmParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// key_type: type.googleapis.com/google.crypto.tink.XAesGcmKey
type XAesGcmKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  uint32         `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Params   *XAesGcmParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	KeyValue []byte         `protobuf:"bytes,3,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
}

func (x *XAesGcmKey) Reset() {
	*x = XAesGcmKey{}
	mi := &file_x_aes_gcm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XAesGcmKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XAesGcmKey) ProtoMessage() {}

func (x *XAesGcmKey) ProtoReflect() protoreflect.Message {
	mi := &file_x_aes_gcm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XAesGcmKey.ProtoReflect.Descriptor instead.
func (*XAesGcmKey) Descriptor() ([]byte, []int) {
	return file_x_aes_gcm_proto_rawDescGZIP(), []int{2}
}

func (x *XAesGcmKey) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *XAesGcmKey) GetParams() *XAesGcmParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *XAesGcmKey) GetKeyValue() []byte {
	if x != nil {
		return x.KeyValue
	}
	return nil
}

var File_x_aes_gcm_proto protoreflect.FileDescriptor

var file_x_aes_gcm_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x78, 0x5f, 0x61, 0x65, 0x73, 0x5f, 0x67, 0x63, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x2e, 0x74, 0x69, 0x6e, 0x6b, 0x22, 0x2c, 0x0a, 0x0d, 0x58, 0x41, 0x65, 0x73, 0x47, 0x63, 0x6d,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x61, 0x6c, 0x74, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x61, 0x6c, 0x74, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x6d, 0x0a, 0x10, 0x58, 0x41, 0x65, 0x73, 0x47, 0x63, 0x6d, 0x4b, 0x65,
	0x79, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x39, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x2e, 0x74, 0x69, 0x6e, 0x6b, 0x2e, 0x58, 0x41, 0x65, 0x73, 0x47, 0x63, 0x6d, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x4a, 0x04, 0x08, 0x02,
	0x10, 0x03, 0x22, 0x7e, 0x0a, 0x0a, 0x58, 0x41, 0x65, 0x73, 0x47, 0x63, 0x6d, 0x4b, 0x65, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x74, 0x69, 0x6e, 0x6b, 0x2e,
	0x58, 0x41, 0x65, 0x73, 0x47, 0x63, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x5c, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2e, 0x74, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x69, 0x6e, 0x6b, 0x2d, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x6e,
	0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x78, 0x5f,
	0x61, 0x65, 0x73, 0x5f, 0x67, 0x63, 0x6d, 0x5f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_x_aes_gcm_proto_rawDescOnce sync.Once
	file_x_aes_gcm_proto_rawDescData = file_x_aes_gcm_proto_rawDesc
)

func file_x_aes_gcm_proto_rawDescGZIP() []byte {
	file_x_aes_gcm_proto_rawDescOnce.Do(func() {
		file_x_aes_gcm_proto_rawDescData = protoimpl.X.CompressGZIP(file_x_aes_gcm_proto_rawDescData)
	})
	return file_x_aes_gcm_proto_rawDescData
}

var file_x_aes_gcm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_x_aes_gcm_proto_goTypes = []any{
	(*XAesGcmParams)(nil),    // 0: google.crypto.tink.XAesGcmParams
	(*XAesGcmKeyFormat)(nil), // 1: google.crypto.tink.XAesGcmKeyFormat
	(*XAesGcmKey)(nil),       // 2: google.crypto.tink.XAesGcmKey
}
var file_x_aes_gcm_proto_depIdxs = []int32{
	0, // 0: google.crypto.tink.XAesGcmKeyFormat.params:type_name -> google.crypto.tink.XAesGcmParams
	0, // 1: google.crypto.tink.XAesGcmKey.params:type_name -> google.crypto.tink.XAesGcmParams
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_x_aes_gcm_proto_init() }
func file_x_aes_gcm_proto_init() {
	if File_x_aes_gcm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_x_aes_gcm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_x_aes_gcm_proto_goTypes,
		DependencyIndexes: file_x_aes_gcm_proto_depIdxs,
		MessageInfos:      file_x_aes_gcm_proto_msgTypes,
	}.Build()
	File_x_aes_gcm_proto = out.File
	file_x_aes_gcm_proto_rawDesc = nil
	file_x_aes_gcm_proto_goTypes = nil
	file_x_aes_gcm_proto_depIdxs = nil
}
